Load DATA
CHARACTERSET UTF8
INFILE *
Append
INTO TABLE batch_charge_addition
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
trailing nullcols
(
  BAN_NO,
  SUBSCRIBER_NO,
  CHARGE_CODE,
  ACTV_REASON_CODE,
  AMOUNT,
  USER_BILL_TEXT,
  MEMO_TEXT,
  EFFECTIVE_DATE DATE "YYYY-MM-DD HH24:MI",
  PROCESS_STATUS,
  PROCESS_TIME,
  STATUS_DESC,
  RECORD_CREATION_DATE,
  REQUEST_ID,
  STREAM,
  REQUEST_USER_ID
)
