Load DATA
CHARACTERSET UTF8
INFILE *
BADFILE RunLoader2017.bad
Append
INTO TABLE batch_discount_addition
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
trailing nullcols
(
  BAN_NO,
  SUBSCRIBER_NO,
  DISCOUNT_CODE,
  MEMO_TEXT,
  PROCESS_STATUS,
  PROCESS_TIME,
  STATUS_DESC,
  REQUEST_ID
)
