Load DATA
CHARACTERSET UTF8
INFILE *
Append
INTO TABLE batch_adjustment_addition
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
trailing nullcols
(
  BAN_NO,
  SUBSCRIBER_NO,
  ADJUSTMENT_CODE,
  MEMO_TEXT,
  USER_BILL_TEXT,
  AMOUNT,
  PROCESS_STATUS,
  PROCESS_TIME,
  STATUS_DESC,
  RECORD_CREATION_DATE,
  REQUEST_ID,
  STREAM,
  REQUEST_USER_ID,
  EFFECTIVE_DATE
)
