load data
into table tb_processing_trans
append
fields terminated by ";" optionally enclosed by '"'
trailing nullcols
(SUBSCRIBER_NO,DEALER_CODE,SALES_AGENT,PRICEPLAN,CAMPAIGN,HANDLE_COMMITMENT,REASON_CODE,MEMO_TEXT,WAIVE_FEES,SUB_TB_SOC,SUB_VPN_CODE,SUB_CUG_CODE,ENTER_TIME,PROCESS_TIME,PROCESS_STATUS,PROCESSED_TYPE,STATUS_DESC,REQUESTOR_ID,REQUEST_TIME,PROCESS_DESCRIPTION)
