Load DATA
CHARACTERSET UTF8
INFILE *
Append
INTO TABLE batch_test_ban_creation
FIELDS TERMINATED BY ";" OPTIONALLY ENCLOSED BY '"'
trailing nullcols
(
  ACCOUNT_TYPE,
  ACCOUNT_SUB_TYPE,
  FIRST_NAME, 
  LAST_NAME, 
  POSTAL_ADDRESS,
  CITY,
  ZIP_CODE,
  OPEN,
  REQUEST_TIME, 
  REQUEST_ID
)
